# Generated by Django 3.0.8 on 2020-07-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-timestamp', '-update'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
