# Generated by Django 3.0.8 on 2020-07-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200715_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-timestamp', '-update'], 'verbose_name': 'post', 'verbose_name_plural': 'Posts'},
        ),
    ]
